[package]
name = "behavioral"
version = "0.1.0"
authors = ["Laurent DELERIS <laurent.deleris@hotmail.fr>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.8"
csv = "0.15.0"
rustc-serialize = "0.3"
